/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.poo.sistemaacademico;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author marco.mazzei
 */
public class CursosTela extends javax.swing.JFrame {

    /**
     * Creates new form CursosTela
     */
    public CursosTela() {
        super("Cursos");               
        initComponents();
        buscarCursos();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cursosComboBox = new javax.swing.JComboBox();
        idCursoTextField = new javax.swing.JTextField();
        nomeCursoTextField = new javax.swing.JTextField();
        tipoCursoTextField = new javax.swing.JTextField();
        adicionarCursoButton = new javax.swing.JButton();
        atualizarCursoButton = new javax.swing.JButton();
        removerCursoButton = new javax.swing.JButton();
        cancelarCursoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de cursos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de cursos"));

        cursosComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cursosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursosComboBoxActionPerformed(evt);
            }
        });

        idCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        idCursoTextField.setEnabled(false);
        idCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCursoTextFieldActionPerformed(evt);
            }
        });

        nomeCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        nomeCursoTextField.setEnabled(false);
        nomeCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeCursoTextFieldActionPerformed(evt);
            }
        });

        tipoCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
        tipoCursoTextField.setEnabled(false);
        tipoCursoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoCursoTextFieldActionPerformed(evt);
            }
        });

        adicionarCursoButton.setText("Novo");
        adicionarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarCursoButtonActionPerformed(evt);
            }
        });

        atualizarCursoButton.setText("Atualizar");
        atualizarCursoButton.setEnabled(false);
        atualizarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCursoButtonActionPerformed(evt);
            }
        });

        removerCursoButton.setText("Remover");
        removerCursoButton.setEnabled(false);
        removerCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCursoButtonActionPerformed(evt);
            }
        });

        cancelarCursoButton.setText("Cancelar");
        cancelarCursoButton.setEnabled(false);
        cancelarCursoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCursoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idCursoTextField)
                    .addComponent(nomeCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(removerCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adicionarCursoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarCursoButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(atualizarCursoButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(88, 88, 88))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nomeCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarCursoButton)
                    .addComponent(atualizarCursoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerCursoButton)
                    .addComponent(cancelarCursoButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCursoTextFieldActionPerformed

    private void nomeCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCursoTextFieldActionPerformed

    private void tipoCursoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoCursoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoCursoTextFieldActionPerformed

    private void adicionarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarCursoButtonActionPerformed
        if (nomeCursoTextField.isEnabled()) {
            String nomeCurso = nomeCursoTextField.getText();
            String tipoCurso = tipoCursoTextField.getText();
            if (nomeCurso == null || nomeCurso.length() == 0 || tipoCurso == null || tipoCurso.length() == 0){
                JOptionPane.showMessageDialog (null, "Preencha curso e tipo");
            }
            else{
                try{
                    int escolha = JOptionPane.showConfirmDialog(null, "Confirmar cadastro de novo curso?");
                    if (escolha == JOptionPane.YES_OPTION){
                        Curso curso = new Curso (nomeCurso, tipoCurso);
                        DAO dao = new DAO();
                        dao.inserirCurso(curso);
                        JOptionPane.showMessageDialog(null, "Curso cadastrado com sucesso");
                        nomeCursoTextField.setText("");
                        tipoCursoTextField.setText("");
                        nomeCursoTextField.setEnabled(false);
                        tipoCursoTextField.setEnabled(false);
                        adicionarCursoButton.setText("Novo");
                        buscarCursos();
                    }
                }
                catch (Exception e){
                    JOptionPane.showMessageDialog(null, "Falha técnica, tente mais tarde");
                    e.printStackTrace();
               }
            }
        } else {
            nomeCursoTextField.setText("");
            tipoCursoTextField.setText("");
            idCursoTextField.setText("");
            nomeCursoTextField.setEnabled(true);
            tipoCursoTextField.setEnabled(true);
            adicionarCursoButton.setText("Salvar");
        }
    }//GEN-LAST:event_adicionarCursoButtonActionPerformed

    private void cancelarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCursoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarCursoButtonActionPerformed

    private void cursosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursosComboBoxActionPerformed
        Curso curso = (Curso) cursosComboBox.getSelectedItem();
        idCursoTextField.setText(Integer.toString(curso.getId()));
        nomeCursoTextField.setText(curso.getNome());
        tipoCursoTextField.setText(curso.getTipo());
        nomeCursoTextField.setEnabled(true);
        tipoCursoTextField.setEnabled(true);
        atualizarCursoButton.setEnabled(true);
        removerCursoButton.setEnabled(true);
    }//GEN-LAST:event_cursosComboBoxActionPerformed

    private void atualizarCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarCursoButtonActionPerformed
       
        int escolha = JOptionPane.showConfirmDialog(null, "Atualizar curso?");
             if (escolha == JOptionPane.YES_OPTION){
                 try{
                     int id = Integer.parseInt (idCursoTextField.getText());
                     String nome = nomeCursoTextField.getText();
                     String tipo = tipoCursoTextField.getText();
                     Curso curso = new Curso (id, nome, tipo);
                     DAO dao = new DAO();
                     dao.atualizarCurso(curso);
                     JOptionPane.showMessageDialog(null, "Curso atualizado com sucesso");
                     buscarCursos();
                     idCursoTextField.setText("");
                     nomeCursoTextField.setText("");
                     tipoCursoTextField.setText("");
                 }
                 catch (Exception e){
                     JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente  mais tarde.");
                     e.printStackTrace();
                 }
            }
    }//GEN-LAST:event_atualizarCursoButtonActionPerformed

    private void removerCursoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCursoButtonActionPerformed
         int escolha = JOptionPane.showConfirmDialog(null, "Remover curso?");
         if (escolha == JOptionPane.YES_OPTION){
             try{
                 int id = Integer.parseInt (idCursoTextField.getText());
                 Curso curso = new Curso(id);
                 DAO dao = new DAO();
                 dao.removerCurso(curso);
                 JOptionPane.showMessageDialog(null, "Curso removido com sucesso!");
                 buscarCursos();
                 nomeCursoTextField.setText("");
                 tipoCursoTextField.setText("");
                 idCursoTextField.setText("");
             }
             catch (Exception e){
                 JOptionPane.showMessageDialog(null, "Falha técnica. Tente novamente mais tarde.");
                 e.printStackTrace();
             }
         }
    }//GEN-LAST:event_removerCursoButtonActionPerformed

    
    private void buscarCursos (){
        try{
            DAO dao = new DAO();
            Curso[] cursos = dao.obterCursos();
            cursosComboBox.setModel(new DefaultComboBoxModel<>(cursos));
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
            e.printStackTrace();
        }
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CursosTela().setVisible(true);
            }
        });
    }
    


    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarCursoButton;
    private javax.swing.JButton atualizarCursoButton;
    private javax.swing.JButton cancelarCursoButton;
    private javax.swing.JComboBox cursosComboBox;
    private javax.swing.JTextField idCursoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCursoTextField;
    private javax.swing.JButton removerCursoButton;
    private javax.swing.JTextField tipoCursoTextField;
    // End of variables declaration//GEN-END:variables
}
